import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AosInit } from './components/aos-init'

const fingerPaint = localFont({
  src: '../../public/fonts/FingerPaint-Regular.ttf',
  weight: '400'
})

const londrinaSolid = localFont({
  src: '../../public/fonts/LondrinaSolid-Regular.ttf',
  weight: '400'
})

const londrinaOutline = localFont({
  src: '../../public/fonts/LondrinaOutline-Regular.ttf',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return(
    <html lang='pt-BR'>
      <body
        className={`${fingerPaint.className} ${londrinaOutline.className} ${londrinaSolid.className} antialiased`}
      >
        {children}
        <AosInit />
      </body>
    </html>
  )
}

export default RootLayout