import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const fingerPaint = localFont({
  src: '../../public/fonts/FingerPaint-Regular.ttf',
  weight: '400'
})

const londrinaSolid = localFont({
  src: [
    {
      path: '../../public/fonts/LondrinaSolid-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/LondrinaSolid-Black.ttf',
      weight: '700'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return(
    <html lang='pt-BR'>
      <body
        className={`${fingerPaint.className} ${londrinaSolid.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}

export default RootLayout